name: Good Idea, Bad Idea
description: Notes on life, design, and everything that’s fucking cool.
url: http://aaroncalzado.com/notes
baseurl: notes
markdown: kramdown
pygments: true
timezone: America/Los_Angeles